/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto3eva;

import java.applet.AudioClip;
import java.util.ArrayList;
import metodos.MetodosMySQL;
/**
 *
 * @author mmoureperez
 */
public class Preguntas extends javax.swing.JFrame {
MetodosMySQL lib = new MetodosMySQL();
ArrayList preguntas = new ArrayList(); 
ArrayList actoresFalsos= new ArrayList();
    /**
     * Creates new form JFrame
     */
    protected  int res,contadora,contadorb;
    protected  String usuario;
    private  String a,b,c,correcta,falsa1,falsa2;
    private int contpreguntas;
    
    AudioClip sonido;
    
    
    public Preguntas() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lPregunta = new javax.swing.JLabel();
        lRespuestaA = new javax.swing.JLabel();
        lRespuestaB = new javax.swing.JLabel();
        lRespuestaC = new javax.swing.JLabel();
        bA = new javax.swing.JButton();
        bB = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bsiguiente = new javax.swing.JButton();
        lNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPregunta.setText("jLabel");

        lRespuestaA.setText("jLabel2");

        lRespuestaB.setText("jLabel1");

        lRespuestaC.setText("jLabel1");

        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });

        bB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBActionPerformed(evt);
            }
        });

        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bsiguiente.setText("Siguiente");
        bsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiguienteActionPerformed(evt);
            }
        });

        lNombre.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addComponent(bsiguiente)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lRespuestaA, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(lRespuestaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lRespuestaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bA, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(bB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRespuestaA)
                    .addComponent(bA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRespuestaB)
                    .addComponent(bB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lRespuestaC)
                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bsiguiente)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        
        if(a.equals(correcta)){
            contadora++;
        }
        else{
            contadorb++;}
       //sonido.stop();
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
    }//GEN-LAST:event_bAActionPerformed

    private void bBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBActionPerformed
        if(b.equals(correcta)){
            contadora++;
        }
        else{
            contadorb++;}
       // sonido.stop();
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
    }//GEN-LAST:event_bBActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
       if(c.equals(correcta)){
            contadora++;
        }
        else{
            contadorb++;}
       // sonido.stop();
        bA.setEnabled(false);
        bB.setEnabled(false);
        bC.setEnabled(false);
    }//GEN-LAST:event_bCActionPerformed

    private void bsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiguienteActionPerformed
       
      
            pregPel();
            bC.setEnabled(true);
            bB.setEnabled(true);
            bA.setEnabled(true);
            contpreguntas++;
               
       if(contpreguntas==5){
            int posicion = (int) Math.floor(Math.random() * 4) + 1;
            switch (posicion) {
                case 1:
                    pregAnillos();
                    break;
                case 2: pregStarWars();
                    break;
                case 3: pregRocky();
                    break;
                case 4: pregGladiator();
                    break;

            }
        }
       if(contpreguntas==6){
           recuento();
          setVisible(false);}
       
    }//GEN-LAST:event_bsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bA;
    private javax.swing.JButton bB;
    private javax.swing.JButton bC;
    private javax.swing.JButton bsiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPregunta;
    private javax.swing.JLabel lRespuestaA;
    private javax.swing.JLabel lRespuestaB;
    private javax.swing.JLabel lRespuestaC;
    // End of variables declaration//GEN-END:variables

public void pregPel(){
    String preg,codAc;
    lNombre.setText(usuario);
    
    lib.Conectar("jdbc:mysql://10.0.0.254/jgarciaamor","jgarciaamor","jgarciaamor");
       
    int id=pregAleatorias();
     preg=lib.consultaDatos("Peliculas WHERE id="+id,2,"Titulo");
     codAc=lib.consultaDatos("Peliculas WHERE id="+id,2,"CODAC1");
     
     correcta=lib.consultaDatos("Actores WHERE CODAC='"+codAc+"'",2,"Nombre");
     falsa1=lib.consultaDatos("ActoresB WHERE CODAC='B"+actoresAleatorios()+"'",2,"Nombre");
     falsa2=lib.consultaDatos("ActoresB WHERE CODAC='B"+actoresAleatorios()+"'",2,"Nombre"); 
     
    lPregunta.setText("Quien aparece en la pelicula "+preg);
    respuestasAleatorias(correcta,falsa1,falsa2);
    
    lib.desconectar();
    actoresFalsos.clear();
}
public void pregStarWars(){
     sonido=java.applet.Applet.newAudioClip(getClass().getResource("/is/Star Wars.wav"));
     sonido.play();
     lPregunta.setText("¿A que pelicula pertenece esta banda sonora?");
     lRespuestaA.setText("Star Wars");
     a=correcta;
     lRespuestaB.setText("El Retorno del Rey");
     lRespuestaC.setText("Rocky");
    bA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/La venganza de los sith.jpeg")));
    bB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/El Retorno del Rey.jpeg")));
    bC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/Rocky.jpeg")));
     }
public void pregAnillos(){
     sonido=java.applet.Applet.newAudioClip(getClass().getResource("/is/El Retorno del Rey.wav"));
     sonido.play();
     lPregunta.setText("¿A que pelicula pertenece esta banda sonora?");
     lRespuestaA.setText("Star Wars");
     lRespuestaB.setText("El Retorno del Rey");
     b=correcta;
     a=falsa1;
     c=falsa2;
     lRespuestaC.setText("Rocky");
    bA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/La venganza de los sith.jpeg")));
    bB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/El Retorno del Rey.jpeg")));
    bC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/Rocky.jpeg")));
     }
public void pregRocky(){
     sonido=java.applet.Applet.newAudioClip(getClass().getResource("/is/Rocky.wav"));
     sonido.play();
     lPregunta.setText("¿A que pelicula pertenece esta banda sonora?");
     lRespuestaA.setText("Star Wars");
     lRespuestaB.setText("El Retorno del Rey");
     lRespuestaC.setText("Rocky");
     c=correcta;
     a=falsa1;
     b=falsa2;
    bA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/La venganza de los sith.jpeg")));
    bB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/El Retorno del Rey.jpeg")));
    bC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/Rocky.jpeg")));
     }
public void pregGladiator(){
     sonido=java.applet.Applet.newAudioClip(getClass().getResource("/is/Gladiator.wav"));
     sonido.play();
     lPregunta.setText("¿A que pelicula pertenece esta banda sonora?");
     lRespuestaA.setText("Gladiator");
     a=correcta;
     a=falsa1;
     c=falsa2;
     lRespuestaB.setText("El Retorno del Rey");
     lRespuestaC.setText("Rocky");
    bA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/Gladiator.jpeg")));
    bB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/El Retorno del Rey.jpeg")));
    bC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/Rocky.jpeg")));}

public void respuestasAleatorias(String correcta,String falsa1, String falsa2){
    
    int posicion=(int)Math.floor(Math.random() * 3)+1;
    switch(posicion){
        case 1: a=correcta;
                b=falsa1;
                c=falsa2;
                
                break;
        case 2: a=falsa1;
                b=correcta;
                c=falsa2;
            break;
        case 3:  a=falsa2;
                 b=falsa1;
                 c=correcta;
            break;
    }
        
    lRespuestaA.setText("a)" + a);

    lRespuestaB.setText("b)" + b);

    lRespuestaC.setText("c)" + c);

    bA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/" + a + ".jpeg")));
    bB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/" + b + ".jpeg")));
    bC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/" + c + ".jpeg")));
}
public void desarrollo(){
    switch(res){
        case 1: contadora++;
            break;
        case 2: contadorb++;
            break;
        case 3: contadorb++;
            break;
    }
}
public  int actoresAleatorios(){
    int valor=0;
        
    for (int i = 0; i < 2; i++) {
        
        valor=(int)Math.floor(Math.random() * 13)+1;
        
    while(actoresFalsos.contains(valor)){
        
      valor=(int)Math.floor(Math.random() * 13)+1;
        
    }    
    actoresFalsos.add(valor);
        
    }return valor;
   }
public int pregAleatorias(){
    int valor;
               
        valor=(int)Math.floor(Math.random() * 13)+1;
        
    while(preguntas.contains(valor)){
        
      valor=(int)Math.floor(Math.random() * 13)+1;}
               
    preguntas.add(valor);

    return valor;}
public void recuento(){
    Resultado r=new Resultado();
    r.setVisible(true);
      
    r.aciertos.setText("Aciertos: "+Integer.toString(contadora));
    r.fallos.setText("Fallos: "+Integer.toString(contadorb));
    lib.Conectar("jdbc:mysql://10.0.0.254/jgarciaamor","jgarciaamor","jgarciaamor");
    String id=lib.consultaDatos("Usuarios WHERE Nombre='"+usuario+"'",2,"Id");
    lib.actualizar("Usuarios",id, "Puntuacion", Integer.toString(contadora));
    lib.desconectar();
    
}

}
